version: '3.9'
services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  generator:
    build: ./generator
    ports:
      - "5000:5000"

  invoker:
    build: ./invoker
    ports:
      - "6000:6000"
    depends_on:
      - redis
      - generator
